version: '3'

services:
  postgres:
    image: postgres
    shm_size: '4gb'
    container_name: asklepios_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=asklepios
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: asklepios_rabbitMQ
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
      - 15692:15692

  seq:
    image: datalust/seq
    container_name: asklepios_seq
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
    ports:
      - 5341:80
    volumes:
      - seq-data:/data

  redis:
    image: redis:7
    container_name: asklepios_redis
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  asklepios-api:
    build:
      context: .
      dockerfile: Asklepios/Asklepios.Api/Dockerfile
    container_name: asklepios_api
    restart: unless-stopped
    ports:
      - 5102:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ__Host=rabbitmq
      - Seq__ServerUrl=http://seq:80
    depends_on:
      - postgres
      - rabbitmq
      - seq
      - redis

  asklepios-web:
    build:
      context: .
      dockerfile: Asklepios.Web/Dockerfile
    container_name: asklepios_web
    restart: unless-stopped
    ports:
      - 8080:80
    depends_on:
      - asklepios-api

volumes:
  postgres:
    driver: local
  seq-data:
    driver: local
  redis-data:
    driver: local
