import { defineStore } from 'pinia'
import { ref } from 'vue'
import { API } from '../services'
import { type User, InputCreateUser} from '@/models/Users/user'
import { type PaginationParams } from '@/models/paginationParams'
