/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    BaseCardWithHover: typeof import('./components/cards/BaseCardWithHover.vue')['default']
    BasePage: typeof import('./components/pages/BasePage.vue')['default']
    ChangeAccountStatusForm: typeof import('./components/users/ChangeAccountStatusForm.vue')['default']
    ChangeUserRoleForm: typeof import('./components/users/ChangeUserRoleForm.vue')['default']
    CreateExaminationForm: typeof import('./components/examinations/CreateExaminationForm.vue')['default']
    DepartmentForm: typeof import('./components/departments/DepartmentForm.vue')['default']
    GenerateUserForm: typeof import('./components/users/GenerateUserForm.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Navigation: typeof import('./components/layout/Navigation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ValidatedTextField: typeof import('./components/ui/ValidatedTextField.vue')['default']
  }
}
