/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AnimatedNumber: typeof import('./components/animations/AnimatedNumber.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    BaseCardWithHover: typeof import('./components/cards/BaseCardWithHover.vue')['default']
    BasePage: typeof import('./components/pages/BasePage.vue')['default']
    ChangeAccountStatusForm: typeof import('./components/users/ChangeAccountStatusForm.vue')['default']
    ChangeUserRoleForm: typeof import('./components/users/ChangeUserRoleForm.vue')['default']
    CreateDoctorForm: typeof import('./components/doctors/CreateDoctorForm.vue')['default']
    CreateExaminationForm: typeof import('./components/examinations/CreateExaminationForm.vue')['default']
    CreateNurseForm: typeof import('./components/nurses/CreateNurseForm.vue')['default']
    CreateOperationForm: typeof import('./components/operations/CreateOperationForm.vue')['default']
    CreatePatientForm: typeof import('./components/patients/CreatePatientForm.vue')['default']
    CreateRoomFom: typeof import('./components/rooms/CreateRoomFom.vue')['default']
    CreateRoomForm: typeof import('./components/rooms/CreateRoomForm.vue')['default']
    DepartmentForm: typeof import('./components/departments/DepartmentForm.vue')['default']
    DepartmentStatistics: typeof import('./components/statistics/DepartmentStatistics.vue')['default']
    EditRoomForm: typeof import('./components/rooms/EditRoomForm.vue')['default']
    GenerateUserForm: typeof import('./components/users/GenerateUserForm.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Navigation: typeof import('./components/layout/Navigation.vue')['default']
    OperationDetails: typeof import('./components/operations/OperationDetails.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ValidatedTextField: typeof import('./components/ui/ValidatedTextField.vue')['default']
  }
}
