name: .NET CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: mydatabase
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672
          - 15672:15672
        options: --health-cmd "rabbitmq-diagnostics ping" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore Asklepios.sln

    - name: Build the project
      run: dotnet build Asklepios.sln

    - name: Wait for services to be ready
      run: |
        for i in {1..10}; do
          if docker exec postgres pg_isready -U postgres -d mydatabase && docker exec rabbitmq rabbitmq-diagnostics ping; then
            echo "Services are ready!"
            break
          fi
          echo "Waiting for services..."
          sleep 5
        done

    - name: Run all tests
      run: dotnet test Asklepios.sln --no-build --verbosity normal
